Replace private api key mention
meilisearch/mini-dashboard pull request #242
Opened 2022-02-14 14:12 UTC by mdubus

# Pull Request

## What does this PR do?
Closes #239

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-02-14 14:42 UTC, bidoubiwa requested changes

2022-02-14 14:42 UTC, bidoubiwa commented on cypress/integration/test-api-key-required.js
> +    cy.contains('Enter your Default Admin API key')
```suggestion
    cy.contains('Enter your admin API key')
```

It does not need to be the default one

2022-02-14 14:42 UTC, bidoubiwa commented on cypress/integration/test-no-api-key-required.js
> +      cy.contains('Enter your Default Admin API key (optional)')
```suggestion
      cy.contains('Enter your admin API key (optional)')
```

2022-02-14 14:42 UTC, bidoubiwa commented on src/App.js
> +            title={`Enter your Default Admin API key${
```suggestion
            title={`Enter your admin API key${
```

2022-02-14 14:42 UTC, bidoubiwa commented on src/components/Header/index.js
> +        title={`Enter your Default Admin API key${
```suggestion
        title={`Enter your admin API key${
```

2022-02-14 14:42 UTC, bidoubiwa commented on src/components/ApiKeyModalContent.js
> +          <strong>search</strong> and <strong>version</strong>{' '}
```suggestion
          At least one API key that gives permission to <strong>get the indexes</strong>,{' '}
          <strong>search</strong> and <strong> get the version of Meilisearch</strong>{' '}
```

2022-02-14 14:42 UTC, bidoubiwa commented on src/components/ApiKeyModalContent.js
> +            actions
```suggestion
```

2022-02-14 14:42 UTC, bidoubiwa commented on src/components/ApiKeyModalContent.js
> +          is required for the dashboard to access the indexes list.
I think this is redundant with the phrase before.

2022-02-16 09:28 UTC, mdubus commented
bors merge

2022-02-16 09:32 UTC, merged