Use digit group formatting for the number of documents
meilisearch/mini-dashboard pull request #273
Opened 2022-06-03 20:04 UTC by agucova

One of the first things I noticed while using the dashboard is how difficult it is to read the number of documents. I'm indexing up to a million entries, and I took me a few seconds to note whether the number of hits or documents was in the hundred of thousands or the millions.

For that reason, I've added locale-aware digit group formatting (the thousands' separator) to both numbers in the interface, which at least for me improves user experience substantially.

I also added some extra breathing space to the stats and the index selector to make space for the added width.

## Screenshots
**Before:**

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/4694408/171943570-0488bd56-7cde-4533-9712-2903e308202e.png">

**After:**
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/4694408/171943633-9565e72e-dfe5-4bbe-b65e-b0f6d9ee9566.png">

2022-06-06 09:00 UTC, mdubus requested changes
Hello @agucova !

Thanks a lot for your PR! This is indeed a great improvement 🤩

Here are a few suggestions in order to improve it, after that it will be ready to merge 💪

Thanks again for your interest in Meilisearch and it's mini-dashboard!

2022-06-06 09:00 UTC, mdubus commented on src/components/Stats.js
> +  const hits = `${nbHits !== nbResults ? '~' : ''} ${nbHits.toLocaleString()}`
Can you rename this variable into `localeNbHits`? 🙏

2022-06-06 09:00 UTC, mdubus commented on src/components/Stats.js
> +// Add 10 px between item
Can you remove this comment? 🙏

2022-06-09 20:39 UTC, agucova commented
@mdubus I've made the changes you requested.

2022-06-13 14:38 UTC, mdubus commented
LGTM 🚀 🔥

bors merge

2022-06-13 14:46 UTC, merged