Add cy.deleteAllIndexes() in before block in test-api-key-required.cy.js
meilisearch/mini-dashboard pull request #336
Opened 2022-10-07 09:29 UTC by shyambh

test-api-key-required.cy.js file

# Pull Request

## Related issue
Fixes #334

## What does this PR do?
- Add cy.deleteAllIndexes() in before block in the test file test-api-key-required.cy.js

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-10-07 09:29 UTC, bidoubiwa commented
Hello @shyambh,
Thank you very much for contributing to Meilisearch :heart:.
However, I am not available on the weekend, but I will be back on Monday :blush:.

*PS: This message was sent automatically!*

2022-10-07 09:30 UTC, shyambh commented
Hi @bidoubiwa , I did exactly what was mentioned in the issue. However, I am not quite sure if this alone would fix the failing test 😅

2022-10-10 08:37 UTC, bidoubiwa requested changes
A part the unecessary new-line, it looks good to me :)

2022-10-10 08:37 UTC, bidoubiwa commented on cypress/e2e/test-api-key-required.cy.js
> +
```suggestion
```

2022-10-10 09:59 UTC, shyambh commented
Hi @bidoubiwa , I have committed the suggested change removing the extra newline.

2022-10-12 08:39 UTC, mdubus commented
Hello @shyambh 👋

First of all, I deeply apologize for the delay 🙈 

This looks perfect, so thanks a lot for your work here  🙏
(thanks also @bidoubiwa for your reviews)

bors merge

2022-10-12 08:46 UTC, merged

2022-10-12 09:17 UTC, shyambh commented
Hi @mdubus , can you please also set the label for this as ```hacktoberfest-accepted``` ?

2022-10-12 11:32 UTC, mdubus commented
Hello @shyambh 👋 

As the PR was made in a repository tagged with the `hacktoberfest` label, there's no need to add the `hacktoberfest-accepted` to your PR, it will count automatically for the Hacktoberfest challenge. The `hacktoberfest-accepted` label is only for specific cases, like a PR that we couldn't merge on time 😉

Have a nice day! ✨

2022-10-12 11:42 UTC, shyambh commented
> 

Thank you very much 🙏🏼